# vim:ft=ansible:

---
- hosts: all
  sudo: yes
  gather_facts: no
  tasks:
    - include: apt/playbook.yml

    - include: database/all.yml
    # - include: database/postgresql/postgresql.yml
    # - include: database/mysql/mysql.yml

    - include: git/git.yml

    - include: redis/redis.yml

    - include: ruby/ruby.yml
    - include: ruby/gem/all.yml
    # - include: ruby/gem/base.yml
    # - include: ruby/gem/rails.yml
    # - include: ruby/gem/rmagick.yml

    - include: vim/vim.yml

    - include: zsh/playbook.yml

