# vim:ft=ansible:

---
- hosts: all
  sudo: yes
  gather_facts: no
  tasks:
    - include: apt/apt.yml
    - include: git/git.yml
    - include: ruby/ruby.yml
    - include: zsh/zsh.yml
    - include: vim/vim.yml

