# vim:ft=ansible:

---
- hosts: all
  sudo: yes
  gather_facts: no
  tasks:
    - include: apt/apt.yml

    - include: database/all.yml
    # - include: database/postgresql/postgresql.yml
    # - include: database/mysql/mysql.yml
    # - include: database/redis/redis.yml

    - include: git/git.yml

    - include: ruby/ruby.yml
    - include: ruby/gem/all.yml
    # - include: ruby/gem/base.yml
    # - include: ruby/gem/rails.yml
    # - include: ruby/gem/rmagick.yml

    # - include: rbenv/rbenv.yml

    - include: vim/vim.yml
    - include: vim/myconf.yml

    - include: zsh/zsh.yml

