# vim:ft=ansible:

---
- hosts: all
  sudo: yes
  gather_facts: no
  tasks:
    - include: apt/playbook.yml
    - include: git/playbook.yml
    - include: ruby/playbook.yml
    - include: zsh/playbook.yml
    - include: vim/playbook.yml

