# vim:ft=ansible:

---
- name: install postgresql
  apt: name={{ item }} state=present
  with_items:
    - libpq-dev
    - postgresql  # 9.3.9
    - python-psycopg2

- name: restarted postgresql
  service:
    name=postgresql
    state=restarted
    enabled=yes

