# vim:ft=ansible:

---
- name: install dependent packages
  apt: name={{ item }} state=present
  with_items:
    - libssl-dev
    - zlib1g-dev
    - libreadline6-dev
    - libffi-dev
    - bison
    - autoconf

- name: exist check
  shell: test -e /usr/local/src/ruby
  register: exist_check
  ignore_errors: yes

- name: git clone
  git: repo=https://github.com/ruby/ruby.git
       dest=/usr/local/src/ruby
       version=v2_2_2
  when: exist_check|failed

- name: compile & install
  shell:
    chdir=/usr/local/src/ruby
    autoconf && ./configure && make && make install

- name: uninstall old version
  apt: name={{ item }} state=absent
  with_items:
    - ruby

