# vim:ft=ansible:

---
- name: install dependent packages
  command: apt-get -y install libssl-dev zlib1g-dev libreadline6-dev libffi-dev bison autoconf

- shell: ls /usr/local/src/ruby
  register: exist_check
  ignore_errors: yes

- name: clone ruby
  git: repo=https://github.com/ruby/ruby.git
       dest=/usr/local/src/ruby
       version=v2_2_2
  when: exist_check|failed

- name: compile & install
  shell:
    chdir=/usr/local/src/ruby
    autoconf && ./configure && make && make install

- name: uninstall old version ruby
  command: apt-get -y remove ruby

