# vim:ft=ansible:

---
- name: exist check
  shell: test -e /tmp/redis-2.8.19
  register: exist_check
  ignore_errors: yes

- name: redis source download
  get_url: >
    url=http://download.redis.io/releases/redis-2.8.19.tar.gz
    dest=/tmp/redis-2.8.19.tar.gz

- name: redis unarchive
  command: >
    tar zxvf redis-2.8.19.tar.gz
    chdir=/tmp/

- name: make
  command: >
    make
    chdir=/tmp/redis-2.8.19

- name: make install
  command: >
    make install
    chdir=/tmp/redis-2.8.19

- name: deamonize on
  replace: >
    dest=/tmp/redis-2.8.19/redis.conf
    regexp='daemonize no'
    replace='daemonize yes'

- name: redis.conf copy
  shell: >
    cp /tmp/redis-2.8.19/redis.conf /etc/redis.conf
    creates=/etc/redis.conf

- name: redis start
  command: >
    redis-server /etc/redis.conf

